give @a holyislands:sacred_grass_block
give @a holyislands:sacred_dirt_block
give @a holyislands:sacred_stone_block
give @a holyislands:sacred_cobblestone_block
give @a holyislands:sacred_oak_log_block
give @a holyislands:sacred_oak_wood_planks_block
give @a holyislands:sacred_oak_leaves_block
give @a holyislands:sacred_tallgrass_1
give @a holyislands:sacred_tallgrass_2
give @a holyislands:sacred_tallgrass_3
give @a holyislands:black_sun_berry_bush_1
give @a holyislands:black_sun_berry_bush_2
give @a holyislands:black_sun_berry_bush_grow
give @a holyislands:pedestal
give @a holyislands:iron_sky_chest
give @a holyislands:mimic_iron_sky_chest
give @a holyislands:mimic_statue
give @a holyislands:sacred_wood_chair
give @a holyislands:sacred_wood_table
give @a holyislands:sacred_stonebrick_block
give @a holyislands:sacred_stonebrick_cracked_block
give @a holyislands:sacred_stonebrick_carved_block
give @a holyislands:small_vessel
give @a holyislands:medium_vessel
give @a holyislands:big_vessel
give @a holyislands:sacred_oak_crafting_table
give @a holyislands:small_royal_vessel
give @a holyislands:medium_royal_vessel
give @a holyislands:big_royal_vessel
give @a holyislands:cloud_block
give @a holyislands:cloud_brick
give @a holyislands:cloud_block_chiseled
give @a holyislands:cloud_block_lines
give @a holyislands:sacred_apple_block